### ISSUE TITLE
Fails to connect with proxy set

### ISSUE THREAD

**Issue by modelmat** [Redrield/elm-ds#1]
![image](https://user-images.githubusercontent.com/25718989/73603457-fc834280-45d6-11ea-9b4e-1098506f70d3.png)
Running either `unset http_proxy HTTP_PROXY && ./elm-ds` (or `http_proxy= HTTP_PROXY= ./elm-ds`) fixes the problem and allows it to boot normally.

However, even when proxy is enabled I can connect to the interface in the chrome by going to the localhost:PORT url.

The console shows a stream of:
```
http://localhost:46575/:1:7: CONSOLE ERROR ReferenceError: Can't find variable: update
http://localhost:46575/:1:7: CONSOLE ERROR ReferenceError: Can't find variable: update
http://localhost:46575/:1:7: CONSOLE ERROR ReferenceError: Can't find variable: update
http://localhost:46575/:1:7: CONSOLE ERROR ReferenceError: Can't find variable: update
```

I have `http_proxy` set to `http://localhost:3128` and a `squid` proxy set up to that address.

**Comment by Redrield** [comment]
What are the configuration options for `squid`?

**Comment by modelmat** [comment]
The (mostly) default options as provided by Arch Linux.
https://hastebin.com/owiyikizuc.nginx

Only changes is changing the shutdown lifetime.
