### ISSUE TITLE
No respond in macOS BigSur 11.2.2

### ISSUE THREAD

**Issue by hayd1n** [Redrield/elm-ds#16]
<img width="1351" alt="截圖 2021-03-09 下午7 28 18" src="https://user-images.githubusercontent.com/31580253/110464794-8e307e00-810e-11eb-86a1-2b584cdd4ceb.png">

No respond in macOS BigSur 11.2.2
Macbook Pro 13 2020
Intel CPU

Download from https://github.com/Redrield/Conductor/actions/runs/506083817

**Comment by Redrield** [comment]
Reproduced with the published artifact. While this is being investigated, the issue doesn't seem to occur if you build the DS from scratch following the steps in the README

**Comment by hayd1n** [comment]
<img width="1482" alt="截圖 2021-03-10 下午2 49 53" src="https://user-images.githubusercontent.com/31580253/110588386-ea97aa00-81af-11eb-9855-f1225a8a90f0.png">

**Comment by Redrield** [comment]
Resolved in d93ba5cf5f64
