### ISSUE TITLE
Prebuilt Artifacts

### ISSUE THREAD

**Issue by memtech3** [Redrield/elm-ds#19]
Where might I find copies of the prebuilt artifacts (particularly the .deb one)?

**Comment by derrell** [comment]
- Click on `Actions` in the top menu bar
- Click on `Build Status` in the left side-bar
- Click on the most recent workflow that shows event `next`. Right now, it's the one called `Revert "Update all deps"`
- Scroll to the bottom. You'll find it there.

**Comment by derrell** [comment]
BTW, there is a dependency you might need to install. I had to do: `sudo apt install libwebkit2gtk-4.0-37` on my Ubuntu 18.04 system.

**Comment by memtech3** [comment]
I can't believe I missed that! Can you add that to the readme?

**Comment by memtech3** [comment]
see pull request @derrell

**Comment by derrell** [comment]
I saw. LGTM. Not my project, though, so we'll await @Redrield to review.
