### ISSUE TITLE
On workstation with two monitors, Conductor consumes both of them

### ISSUE THREAD

**Issue by derrell** [Redrield/elm-ds#20]
Very cool project!

Request that the Conductor window be resizeable so that it can be constrained to a single monitor (or even a small portion of a single monitor). Ideally, the content would shrink as necessary, down to some minimum required size for each widget, allowing the DS to be as small, or nearly so, as a user desires. As a minimum implementation request, though, it should be allowed to be told to consume only the width of a single monitor.

**Comment by memtech3** [comment]
I second that, just ran into that issue

**Comment by Redrield** [comment]
It seems like naively using X11 screen resolution doesn't give the expected results, please try to compile the latest code at https://github.com/Redrield/Conductor/tree/fix/window-sizing (Assuming using Linux, I'll work on macOS support later) and advise if it works. I'm not sure if there's a way to ensure that the window gets spawned on the screen it was sized for, but hopefully it shouldn't take up both monitors now

**Comment by derrell** [comment]
Thanks, @Redrield. I'll give this a try during the weekend.

**Comment by derrell** [comment]
I can confirm that the `window-sizing` branch solves the problem of the DS window consuming both screens. It now takes up about 3/4 of one screen, for me. Thanks!

**Comment by Redrield** [comment]
@derrell Sorry to bug again, but I don't have a multi-monitor workstation to ensure changes work. Could you try the latest commit I just pushed? Will simplify the code immensely as I wouldn't need to write the platform code myself

**Comment by derrell** [comment]
Confirmed, @Redrield. Commit cd2b670 also properly displays the DS on only a single monitor. Thanks.
