### ISSUE TITLE
Syntax error: Expected “,” but found identifier. (-2741)

### ISSUE THREAD

**Issue by AnanthVivekanand** [Redrield/elm-ds#33]
When running the latest MacOS artifact or compiling from source, I get the error: `282:289: syntax error: Expected “,” but found identifier. (-2741)`.

```
➜ ./conductor
Webserver launched on port 56191
Detected Resolution 1680 1050
Resized 1328 441
282:289: syntax error: Expected “,” but found identifier. (-2741)
```

![image](https://user-images.githubusercontent.com/40674932/121789025-fd978d00-cb97-11eb-8a99-b3481eedab4e.png)

**Comment by Redrield** [comment]
System info please; macOS version, etc

**Comment by prateekma** [comment]
What compiler version?

**Comment by AnanthVivekanand** [comment]
MacOS Big Sur, version 11.2.3. 

I'm not sure if this is the compiler version, I have rustc version 1.51.0.

**Comment by Redrield** [comment]
@prateekma This looks like an applescript error but I have *no* clue what would be causing it, could you see if it can be reproduced and bisect?

**Comment by prateekma** [comment]
I could not reproduce when compiling from source.

**Comment by prateekma** [comment]
@AnanthVivekanand Do you have the Xcode Command Line Tools installed? Might be worth giving that a shot.

**Comment by AnanthVivekanand** [comment]
Yes, I have the Xcode Command Line Tools installed. `xcode-select --version` indicates I have version 2384 installed and `xcode-select --install` also says that command line tools are already installed. 

Not sure if this is related, but looking through the Github actions logs, I noticed multiple errors of the nodejs package 'nan' not being found: https://github.com/Redrield/Conductor/runs/2560532326?check_suite_focus=true#step:5:55. These occur when I build from source as well.

**Comment by Redrield** [comment]
Stale issue couldn't be reproduced. Please feel free to re-open if more relevant information surfaces.
