### ISSUE TITLE
Any plan to update for 2023?

### ISSUE THREAD

**Issue by Aldhanekaa** [Redrield/elm-ds#36]
I'm curious, if you guys had any plan to do that. The kickoff already started, I might need help to work on FRC on this beautiful software. (I'm using MacOS, it works good for FRC 2022 though)

**Comment by Aldhanekaa** [comment]
oh wait, it just worked on my macos. Idk why at first I couldn't connect my conductor (macos version) to the robot, but after I restarted it, it works!

**Comment by Redrield** [comment]
To answer the original question, this is a project that'll work until it doesn't. I don't really have access to a RIO anymore, and even if I did I doubt the person who originally reveng'd the protocol (which I used as the basis for my implementation) would have access to do so again in the event of a major change
